name: Build and Test
on: 
  push:
    branches: '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          export OPENSSL_CONF=/dev/null
          npm install
          npm run test
